# Generated by Django 5.2.6 on 2025-09-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_vehicle_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
